### ISSUE TITLE
Error while giving value 0 to parameter "specify-arg"

### ISSUE THREAD

**Issue by aanchalMongia** [stephenliu0423/PyDTI#1]
Dear author,
Thanks for the amazing work!
I was trying to run the pyDTI.py file.
The following command runs fine:

`>python PyDTI.py --method="nrlmf" --dataset="nr" --cvs=1 --specify-arg=1 --data-dir=".\\data" `

but when "specify-arg" parameter is given value 0 (to run the code for optimal paramters),

`>python PyDTI.py --method="nrlmf" --dataset="nr" --cvs=1 --specify-arg=0 --data-dir=".\\data"`

The following error is thrown by the code:
```
Traceback (most recent call last):
  File "PyDTI.py", line 127, in <module>
    main(sys.argv[1:])
  File "PyDTI.py", line 80, in main
    cv_eval.nrlmf_cv_eval(method, dataset, cv_data, X, D, T, cvs, args)
  File "D:\AanchalMongia_phdClg\Phd\Matlab\MatlabWorkspace\Prob11_grmcImpute\extras\Baseline_NRLMF\cv_eval.py", line 20, in nrlmf_cv_eval
    model = NRLMF(cfix=para['c'], K1=para['K1'], K2=para['K2'], num_factors=r, lambda_d=2**(x), lambda_t=2**(x), alpha=2**(y), beta=2**(z), theta=2**(t), max_iter=100)
ValueError: Integers to negative integer powers are not allowed.
```

**Comment by zuobaifu** [comment]
请问一下问题解决了吗
